// <auto-generated />
namespace iPede.Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rename_ProductImage_ProductImageId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_ProductImage_ProductImageId));
        
        string IMigrationMetadata.Id
        {
            get { return "201605140418525_Rename_ProductImage_ProductImageId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
