// <auto-generated />
namespace Isofrio.Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BannerItem_VerticalPosition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BannerItem_VerticalPosition));
        
        string IMigrationMetadata.Id
        {
            get { return "201509281826396_BannerItem_VerticalPosition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
